project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Nicholas J Lyon"
  favicon: images/logo_lyon.png
  repo-url: https://github.com/njlyon0/njlyon0.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Software"
        href: software.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Papers"
        href: pubs.qmd
      - text: "Presentations"
        href: talks.qmd
      - text: "Consulting"
        href: consult.qmd
    right:
      - icon: github
        href: https://github.com/njlyon0
  page-footer:
    center: "Copyright 2024, Nicholas Lyon"
    background: secondary

format:
  html:
    theme:
      light: lyonlight.scss
      dark: lyondark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
