project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Nicholas J Lyon"
  favicon: images/logo_lyon.png
  repo-url: https://github.com/njlyon0/njlyon0.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Data Science Portfolio"
        menu:
         - href: pkgs.qmd
         - href: workshops.qmd
         - text: R/Python Bilingualism
           href: https://njlyon0.github.io/collab_bilingualism/
         - href: shiny.qmd
         - href: code.qmd
      - text: "Academic Portfolio"
        menu:
         - href: talks.qmd
         - href: pubs.qmd
      - href: consult.qmd
    right:
      - icon: github
        href: https://github.com/njlyon0
      - text: CV
        href: https://github.com/njlyon0/njlyon0.github.io/blob/main/files/LyonCV.pdf
  page-footer:
    center: "Copyright 2023, Nicholas Lyon"
    background: secondary

format:
  html:
    theme:
      light: lyonlight.scss
      dark: lyondark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
