project:
  type: website
  output-dir: docs

website:
  title: "Nicholas J Lyon"
  favicon: images/dndR_hex.png
  repo-url: https://github.com/njlyon0/njlyon0.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - career.qmd
      - pkgs.qmd
      - talks.qmd
      - pubs.qmd
    right:
      - icon: github
        href: https://github.com/njlyon0
      - text: CV
        href: https://github.com/njlyon0/njlyon0.github.io/blob/main/files/LyonCV.pdf
      - icon: twitter
        href: https://twitter.com/scilyon
  page-footer:
    center: "Copyright 2022, Nicholas Lyon"
    background: secondary

format:
  html:
    theme:
      light: lyonlight.scss
      dark: lyondark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false

