project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Nicholas J Lyon"
  favicon: images/hex_logos/dndR_hex.png
  repo-url: https://github.com/njlyon0/njlyon0.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Data Science Portfolio"
        menu:
         - pkgs.qmd
         - workshops.qmd
         - shiny.qmd
         - code.qmd
      - text: "Academic Portfolio"
        menu:
         - talks.qmd
         - pubs.qmd
      - consult.qmd
    right:
      - icon: github
        href: https://github.com/njlyon0
      - text: CV
        href: https://github.com/njlyon0/njlyon0.github.io/blob/main/files/LyonCV.pdf
  page-footer:
    center: "Copyright 2023, Nicholas Lyon"
    background: secondary

format:
  html:
    theme:
      light: lyonlight.scss
      dark: lyondark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
