project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute:
  freeze: auto

website:
  title: "Nicholas J Lyon"
  favicon: images/logo_lyon.png
  repo-url: https://github.com/njlyon0/njlyon0.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Software"
        href: software.qmd
      - text: "Tips"
        menu:
          - text: "{{< fa brands git >}} -- Conventional Commits"
            href: tips/commits.qmd
          - text: "{{< fa brands r-project >}} -- Class Coercion"
            href: tips/r_class-coercion.qmd
          - text: "{{< fa brands r-project >}} -- Condition Signalling"
            href: tips/r_conditions.qmd
          - text: "{{< fa brands r-project >}} -- Selecting Elements"
            href: tips/r_select-elements.qmd
          - text: "{{< fa brands r-project >}} -- Loop Syntax"
            href: tips/r_int-loops.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Papers"
        href: pubs.qmd
      - text: "Presentations"
        href: talks.qmd
      - text: "Consulting"
        href: consult.qmd
    right:
      - icon: github
        href: https://github.com/njlyon0
  page-footer:
    center: "Copyright 2024, Nicholas Lyon"
    background: secondary

format:
  html:
    theme:
      light: _extensions/njlyon0/lyon_theme/lyon_light.scss
      dark: _extensions/njlyon0/lyon_theme/lyon_dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    code-annotations: hover
