project:
  type: website

website:
  title: "Nicholas J Lyon"
  page-footer: "Copyright 2022, Nicholas Lyon"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - talks.qmd
      - pubs.qmd
    right:
      - icon: github
        href: https://github.com/njlyon0
      - icon: twitter
        href: https://twitter.com/scilyon

format:
  html:
    theme: united
    css: styles.css
    toc: true

