project:
  type: website
  output-dir: docs

website:
  title: "Nicholas J Lyon"
  repo-url: https://github.com/njlyon0/lyon_quarto
  repo-actions: [issue]
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - talks.qmd
      - pubs.qmd
    right:
      - icon: github
        href: https://github.com/njlyon0
      - icon: twitter
        href: https://twitter.com/scilyon
  page-footer:
    center: "Copyright 2022, Nicholas Lyon"
    background: secondary

format:
  html:
    theme: united
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false

